version: '3.8'

services:
  backend:
    build: 
      context: ./caption_backend
      dockerfile: Dockerfile
    container_name: caption_backend
    ports:
      - "8000:8000"
    env_file:
      - ./caption_backend/.env


  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: caption_frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./front-end/.env.local
