# Generated by Django 5.1.7 on 2025-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captionrating',
            name='caption',
        ),
        migrations.AddField(
            model_name='captionrating',
            name='caption_basic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captionrating',
            name='caption_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captionrating',
            name='caption_refined',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captionrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caption_images/'),
        ),
    ]
