# Generated by Django 5.1.7 on 2025-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_captionrating_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionrating',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
