# Generated by Django 5.1.6 on 2025-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_hashtags_ratedcaption_generated_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedcaption',
            name='generated_hashtags',
        ),
        migrations.AddField(
            model_name='ratedcaption',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
